version: '3'

# For development purpose only
services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - 3364:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hackernews
    volumes:
      - data:/var/lib/mysql

  web:
    image: dev_hackernews:1.0.0
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./fileBucket:/code/fileBucket
    ports:
      - 80:80
    links:
      - db:mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    ports:
      - 8080:80
    links:
      - db:mysql
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    depends_on:
      - db

volumes:
  data:
