version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3364:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hackernews
    volumes:
      - data:/var/lib/mysql
    networks:
      - webnet

  web:
    image: deploy_hackernews:1.0.0
    container_name: app
    command: python manage.py runserver 80
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    links:
      - db:mysql
    environment:
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
    networks:
      - webnet
    depends_on:
      - db

volumes:
  data:

networks:
  webnet:
