version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysqldb
    ports:
      - 3364:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hackernews
    volumes:
      - data:/var/lib/mysql
  web:
    image: hackernews:1.0.0
    container_name: app
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8088:80"
    links:
      - db:mysql
    container_name: phpMyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always

volumes:
  data:
