#!/bin/bash

# $0 is the filename of the executing file
# getting directory name of the current executing file
# and setting parent directory as PROJECT_PATH
export PROJECT_PATH="$(dirname $0)/.."
cd $PROJECT_PATH

docker-compose -f deploy.yml down
docker volume prune
docker-compose -f deploy.yml up -d --build

tput setaf 2
echo "Wait for it..."

# This particular sleep time is because mysql takes time to start
# and get setup. Therefore give enough time for it to start.
# If not, throws connection refused error.
sleep 10
docker-compose -f deploy.yml run web python manage.py makemigrations
docker-compose -f deploy.yml run web python manage.py migrate

docker-compose -f deploy.yml down  # To terminate unnecessary containers
docker-compose -f deploy.yml up -d

docker container exec app python ../backend/htmlDownloader.py --path /code/fileBucket --filename something.html --level 3
docker container exec app python ../backend/htmlParser.py --path /code/fileBucket --filename something.html

tput setaf 2
echo "Okay! Now you can load http://localhost to see the output"

# Commented this out as it wasn't working in mac OS
# docker swarm init
# docker stack deploy -c deploy.yml news

# Altenate deployment plan instead of stack deploy
# docker-compose up -d
