# Generated by Django 2.1.4 on 2018-12-16 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(match='.*\\.htm(l)?', path='/code/fileBucket', unique=True)),
                ('pagination', models.IntegerField(default=1, verbose_name='Paginations')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('modified_at', models.DateTimeField(verbose_name='modified at')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('post_age', models.DurationField(default=datetime.timedelta, verbose_name='post age')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('modified_at', models.DateTimeField(verbose_name='modified at')),
                ('hacker_news_url', models.URLField(verbose_name='hacker news url')),
                ('upvotes', models.IntegerField(verbose_name='number of upvotes')),
                ('comments', models.IntegerField(verbose_name='number of comments')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
        ),
    ]
