# Generated by Django 2.1.4 on 2018-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FilePathField(match='*.htm(l)?', path='/code/fileBucket')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
                ('modified_at', models.DateTimeField(verbose_name='modified at')),
            ],
        ),
    ]
