# Generated by Django 2.1.4 on 2018-12-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181216_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='file_path',
            field=models.FilePathField(match='.*\\.htm(l)?', path='/code/fileBucket', unique=True),
        ),
    ]
