# Generated by Django 2.1.4 on 2018-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181216_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor',
            name='pagination',
            field=models.IntegerField(default=1, verbose_name='Paginations'),
        ),
    ]
